// <auto-generated />
using System;
using BlogBank.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogBank.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260501182817_InitialCreatPg")]
    partial class InitialCreatPg
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BlogBank.Core.Entities.Article", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("所属分类，例如：前端开发、JavaScript、DevOps");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("文章正文（HTML 格式）");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)")
                        .HasComment("创建时间");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasComment("发布日期");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasComment("文章摘要，用于列表页展示");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ReadTime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("预计阅读时长，例如：5 分钟阅读");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasComment("文章标题");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)")
                        .HasComment("修改时间");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("articles", null, t =>
                        {
                            t.HasComment("博客文章");
                        });
                });

            modelBuilder.Entity("BlogBank.Core.Entities.ArticleTag", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    b.Property<long>("ArticleId")
                        .HasColumnType("bigint")
                        .HasComment("所属文章 ID（外键）");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)")
                        .HasComment("创建时间");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("标签名称，例如：CSS、响应式");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)")
                        .HasComment("修改时间");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("article_tags", null, t =>
                        {
                            t.HasComment("文章标签");
                        });
                });

            modelBuilder.Entity("BlogBank.Core.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasComment("操作类型：增/删/改/查");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("操作的数据记录ID");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("客户端IP地址");

                    b.Property<string>("NewValues")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("修改后的值（JSON格式）");

                    b.Property<string>("OldValues")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("修改前的值（JSON格式）");

                    b.Property<DateTime>("OperatedAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("操作时间");

                    b.Property<string>("RequestUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasComment("请求接口地址");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("操作的数据表名");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("操作人ID");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("操作人姓名");

                    b.HasKey("Id");

                    b.HasIndex("OperatedAt")
                        .HasDatabaseName("IX_audit_logs_operated_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_audit_logs_user_id");

                    b.ToTable("audit_logs", null, t =>
                        {
                            t.HasComment("操作审计日志");
                        });
                });

            modelBuilder.Entity("BlogBank.Core.Entities.Essay", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    b.Property<string>("BgColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("卡片背景色，十六进制颜色值，例如：#fef3c7");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("随笔正文（纯文本）");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)")
                        .HasComment("创建时间");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasComment("发布日期");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasComment("随笔摘要，用于列表页折叠展示");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasComment("写作地点，例如：街角咖啡馆");

                    b.Property<string>("Mood")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("心情文字描述，例如：惬意、专注");

                    b.Property<string>("MoodIcon")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasComment("心情 Emoji 图标，例如：😌");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasComment("随笔标题");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)")
                        .HasComment("修改时间");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Weather")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("天气文字描述，例如：晴、多云");

                    b.Property<string>("WeatherIcon")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasComment("天气 Emoji 图标，例如：☀️");

                    b.HasKey("Id");

                    b.ToTable("essays", null, t =>
                        {
                            t.HasComment("随笔");
                        });
                });

            modelBuilder.Entity("BlogBank.Core.Entities.EssayTag", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)")
                        .HasComment("创建时间");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("EssayId")
                        .HasColumnType("bigint")
                        .HasComment("所属随笔 ID（外键）");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("标签名称，例如：生活、咖啡");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)")
                        .HasComment("修改时间");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EssayId");

                    b.ToTable("essay_tags", null, t =>
                        {
                            t.HasComment("随笔标签");
                        });
                });

            modelBuilder.Entity("BlogBank.Core.Entities.Menu", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    b.Property<string>("Component")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasComment("组件文件路径，相对于 views 目录");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)")
                        .HasComment("创建时间");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Icon")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasComment("菜单图标，格式如 ele-Menu");

                    b.Property<bool>("IsAffix")
                        .HasColumnType("tinyint(1)")
                        .HasComment("是否固定在标签栏，固定后不可关闭");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHide")
                        .HasColumnType("tinyint(1)")
                        .HasComment("是否在侧边栏中隐藏");

                    b.Property<bool>("IsIframe")
                        .HasColumnType("tinyint(1)")
                        .HasComment("是否以内嵌 iframe 方式打开");

                    b.Property<bool>("IsKeepAlive")
                        .HasColumnType("tinyint(1)")
                        .HasComment("是否开启页面缓存（keep-alive）");

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasComment("路由名称，对应前端 Vue Router name 字段");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int")
                        .HasComment("排序号，数值越小越靠前");

                    b.Property<string>("OutLink")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasComment("外链 URL");

                    b.Property<string>("Path")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasComment("路由地址，对应前端 Vue Router path 字段");

                    b.Property<string>("Permission")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasComment("权限标识，格式如 sys:user:add");

                    b.Property<long>("Pid")
                        .HasColumnType("bigint")
                        .HasComment("父菜单 ID，根菜单为 0");

                    b.Property<string>("Redirect")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasComment("重定向地址，目录类型使用");

                    b.Property<string>("Remark")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasComment("备注");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasComment("菜单状态：0 禁用、1 启用");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasComment("菜单显示名称");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasComment("菜单类型：1 目录、2 菜单、3 按钮");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)")
                        .HasComment("修改时间");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("menus", null, t =>
                        {
                            t.HasComment("系统菜单");
                        });
                });

            modelBuilder.Entity("BlogBank.Core.Entities.Role", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("角色编码，程序内部使用，全局唯一，例如：admin、editor");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)")
                        .HasComment("创建时间");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasComment("角色描述，说明该角色的权限范围");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("角色显示名称，例如：管理员、编辑者");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)")
                        .HasComment("修改时间");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("roles", null, t =>
                        {
                            t.HasComment("角色");
                        });
                });

            modelBuilder.Entity("BlogBank.Core.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasComment("头像 URL");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)")
                        .HasComment("创建时间");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasComment("邮箱地址，全局唯一");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasComment("账号是否启用");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("显示昵称");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasComment("经过哈希处理的密码");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)")
                        .HasComment("最后更新时间");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("用户名，用于登录，全局唯一");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", null, t =>
                        {
                            t.HasComment("用户");
                        });
                });

            modelBuilder.Entity("BlogBank.Core.Entities.UserMenu", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasComment("关联的用户 ID（联合主键之一）");

                    b.Property<long>("MenuId")
                        .HasColumnType("bigint")
                        .HasComment("关联的菜单 ID（联合主键之一）");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("授权时间");

                    b.HasKey("UserId", "MenuId");

                    b.HasIndex("MenuId");

                    b.ToTable("user_menus", null, t =>
                        {
                            t.HasComment("用户菜单关联");
                        });
                });

            modelBuilder.Entity("BlogBank.Core.Entities.UserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasComment("关联的用户 ID（联合主键之一）");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasComment("关联的角色 ID（联合主键之一）");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("授权时间");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", null, t =>
                        {
                            t.HasComment("用户角色关联");
                        });
                });

            modelBuilder.Entity("BlogBank.Core.Entities.ArticleTag", b =>
                {
                    b.HasOne("BlogBank.Core.Entities.Article", "Article")
                        .WithMany("Tags")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("BlogBank.Core.Entities.EssayTag", b =>
                {
                    b.HasOne("BlogBank.Core.Entities.Essay", "Essay")
                        .WithMany("Tags")
                        .HasForeignKey("EssayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Essay");
                });

            modelBuilder.Entity("BlogBank.Core.Entities.UserMenu", b =>
                {
                    b.HasOne("BlogBank.Core.Entities.Menu", "Menu")
                        .WithMany("UserMenus")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogBank.Core.Entities.User", "User")
                        .WithMany("UserMenus")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlogBank.Core.Entities.UserRole", b =>
                {
                    b.HasOne("BlogBank.Core.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogBank.Core.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlogBank.Core.Entities.Article", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("BlogBank.Core.Entities.Essay", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("BlogBank.Core.Entities.Menu", b =>
                {
                    b.Navigation("UserMenus");
                });

            modelBuilder.Entity("BlogBank.Core.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("BlogBank.Core.Entities.User", b =>
                {
                    b.Navigation("UserMenus");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
